// Package client is the canonical Go client for ledger. Generated by
// vikrant from the service's proto and service.yaml; do not edit. It is
// regenerated whenever either changes.
//
// Import it from another service on the platform:
//
//	go get github.com/smallStepGiantLeap/ledger/client@latest
//
//	cc, err := client.Dial(client.Target)
//	...
//	c := ledgerv1.NewLedgerServiceClient(cc)
//
// What the platform decides for you, and why:
//
//   - Deadlines: every unary method gets a default deadline (10s) when
//     the caller sets none. It travels to the server as grpc-timeout, so the
//     server stops working on a call its caller has given up on. Streaming
//     methods get none: a deadline would cut a healthy long-lived stream.
//   - No retry policy here. Retries happen once, in the mesh, driven by the
//     proto: methods marked idempotent are retried on UNAVAILABLE; the rest
//     only when the request never reached the server. Retrying in both
//     places would multiply attempts.
//   - No client-side load balancing or health checking. Inside the mesh this
//     connection goes to the local sidecar, which balances every request
//     across healthy replicas; a health watch here would see one replica and
//     mark the whole service down while that replica drains.
//   - Keepalive pings every 20s after silence, well above the server's 10s
//     enforcement floor, so the platform never answers with too_many_pings.
//   - Reconnect backoff from 100ms up to 5s instead of grpc-go's 1s-120s, so
//     a restarted peer is reachable again within seconds.
//   - Trace context: every call sends the W3C traceparent of its context,
//     using the global propagator (services the platform generates install
//     it at startup), so the mesh's spans for this call join the caller's
//     trace instead of starting a new one.
package client

import (
	"time"

	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/backoff"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/keepalive"
)

// Target is the service's address inside the mesh. The sidecar encrypts and
// authenticates the connection (mTLS), so the application dials plaintext.
const Target = "dns:///ledger.ledger.svc.cluster.local:50051"

// ServiceConfig sets per-method defaults derived from the proto.
const ServiceConfig = `{"methodConfig":[{"name":[{"service":"ledger.v1.LedgerService","method":"GetBalance"}],"timeout":"10s"},{"name":[{"service":"ledger.v1.LedgerService","method":"Transfer"}],"timeout":"10s"}]}`

// DialOptions are the platform's client defaults. Options passed to Dial are
// applied after these and win.
func DialOptions() []grpc.DialOption {
	bo := backoff.DefaultConfig
	bo.BaseDelay = 100 * time.Millisecond
	bo.MaxDelay = 5 * time.Second
	return []grpc.DialOption{
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithDefaultServiceConfig(ServiceConfig),
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
		grpc.WithConnectParams(grpc.ConnectParams{Backoff: bo, MinConnectTimeout: 5 * time.Second}),
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                20 * time.Second,
			Timeout:             5 * time.Second,
			PermitWithoutStream: true,
		}),
	}
}

// Dial creates a client connection to target with the platform's defaults.
// It does not block: the connection is made on the first RPC.
func Dial(target string, extra ...grpc.DialOption) (*grpc.ClientConn, error) {
	return grpc.NewClient(target, append(DialOptions(), extra...)...)
}
