# syntax=docker/dockerfile:1
# Generated by vikrant v0.1.0 from service.yaml. Do not edit: platform-owned.
#
# Two stages. The build stage compiles a static binary; the runtime image is
# distroless/static:nonroot plus exactly one layer, the binary: no shell, no
# package manager, and it runs as uid 65532, which PSS "restricted" requires.
# Base images are pinned by digest so a moved tag cannot change what ships.

# The build stage runs on the builder's own platform and cross-compiles, so
# one build publishes amd64 and arm64 without emulation.
FROM --platform=$BUILDPLATFORM golang:1.25@sha256:699337d620559a59b4a2bb298ad59611e535d2ee755a34cf2d2a98f37578dc80 AS build
ARG TARGETOS TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
COPY client/go.mod client/go.sum ./client/
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o /out/server ./cmd/ledger

FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
COPY --from=build /out/server /server
USER 65532:65532
EXPOSE 50051 9090
ENTRYPOINT ["/server"]
