# Generated by vikrant v0.1.0. Do not edit: platform-owned.

IMAGE ?= ledger:dev
BIN   := $(CURDIR)/bin
export PATH := $(BIN):$(PATH)

.PHONY: tools build test generate check-generated check-stamp image run e2e e2e-down

tools: ## the exact code generators the platform used
	GOBIN=$(BIN) go install github.com/bufbuild/buf/cmd/buf@v1.64.0
	GOBIN=$(BIN) go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.12
	GOBIN=$(BIN) go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.0

build:
	go build ./...
	cd client && go build ./...

test:
	go test -race -count=1 ./...
	cd client && go test -race -count=1 ./...

generate:
	buf generate

# The committed stubs must be exactly what the pinned generators produce.
check-generated: generate
	git diff --exit-code -- client/gen || (echo "client/gen is out of date with the proto"; exit 1)

# Platform-owned files must match what the platform rendered from service.yaml
# and the proto. A mismatch means one was edited by hand, or service.yaml or
# the proto changed and the platform has not regenerated yet.
check-stamp:
	@sha256sum --check --quiet .platform/sha256sums || \
	  (echo "platform-owned files do not match service.yaml; the platform regenerates them on push"; exit 1)

image:
	docker build --provenance=false -t $(IMAGE) .

run:
	go run ./cmd/ledger

# Run this service in a box: kind + Istio (CNI) + Argo Rollouts + KEDA, with
# its dependencies, and prove every access rule, PSS, autoscaling and a
# canary rollout. Idempotent.
e2e:
	e2e/run.sh

e2e-down:
	e2e/run.sh down
