// Package server builds this service's hardened *grpc.Server. Generated by
// vikrant as a starting point: this file now belongs to the service team.
//
// Every protection is a field in Options; each comment gives grpc-go's own
// default and the reason for the value Defaults() chooses.
package server

import (
	"flag"
	"strconv"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"

	"github.com/smallStepGiantLeap/ledger/internal/platform/metrics"
)

// Options configures the server. A zero duration or size means grpc-go's
// default.
type Options struct {
	// MaxConcurrentStreamsPerConn caps streams on one HTTP/2 connection.
	// grpc-go default: unbounded.
	MaxConcurrentStreamsPerConn uint32
	// MaxInflightStreams and MaxInflightUnary are global admission limits.
	// Beyond them new RPCs fail fast with RESOURCE_EXHAUSTED instead of
	// queueing. Size them to memory: a stream whose client stops reading can
	// pin about 80 KiB (grpc-go's 64 KiB per-stream write quota plus state),
	// so MaxInflightStreams x 80 KiB must fit the pod's memory limit.
	MaxInflightStreams int
	MaxInflightUnary   int
	// MaxRecvMsgSize: grpc-go default 4 MiB. MaxSendMsgSize: grpc-go default
	// math.MaxInt32; capped so a bug cannot build a 2 GiB reply.
	MaxRecvMsgSize int
	MaxSendMsgSize int
	// MaxHeaderListSize caps request metadata. grpc-go default 16 MiB.
	MaxHeaderListSize uint32
	// ConnectionTimeout bounds the handshake; a client that connects and
	// says nothing is dropped. grpc-go default 120s.
	ConnectionTimeout time.Duration
	// MaxUnaryTimeout caps every unary deadline, including callers that send
	// none. No grpc-go equivalent.
	MaxUnaryTimeout time.Duration
	// KeepaliveMinTime: clients pinging more often get GOAWAY
	// ENHANCE_YOUR_CALM "too_many_pings". grpc-go default 5m.
	KeepaliveMinTime             time.Duration
	KeepalivePermitWithoutStream bool
	// KeepaliveTime/Timeout: ping a silent connection, close it if no reply.
	// Reaps clients that vanished without FIN. grpc-go default 2h / 20s.
	KeepaliveTime    time.Duration
	KeepaliveTimeout time.Duration
	// MaxConnectionIdle closes connections with no RPCs. grpc-go: infinity.
	MaxConnectionIdle time.Duration
	// MaxConnectionAge sends GOAWAY (no new RPCs on this connection) after
	// this age, +/-10% jitter; MaxConnectionAgeGrace then closes it. Bounds
	// how long a connection, and a client that stopped reading, can pin this
	// replica. grpc-go default: infinity for both.
	MaxConnectionAge      time.Duration
	MaxConnectionAgeGrace time.Duration
}

// Defaults are the platform's values, sized for a pod with a 512 MiB limit.
func Defaults() Options {
	return Options{
		MaxConcurrentStreamsPerConn:  1000,
		MaxInflightStreams:           4000, // x 80 KiB = 312 MiB worst case
		MaxInflightUnary:             2000,
		MaxRecvMsgSize:               4 << 20,
		MaxSendMsgSize:               4 << 20,
		MaxHeaderListSize:            16 << 10,
		ConnectionTimeout:            10 * time.Second,
		MaxUnaryTimeout:              30 * time.Second,
		KeepaliveMinTime:             10 * time.Second,
		KeepalivePermitWithoutStream: true,
		KeepaliveTime:                30 * time.Second,
		KeepaliveTimeout:             10 * time.Second,
		MaxConnectionIdle:            5 * time.Minute,
		MaxConnectionAge:             5 * time.Minute,
		MaxConnectionAgeGrace:        1 * time.Minute,
	}
}

// RegisterFlags binds the options to flags, defaulting to the current values.
func (o *Options) RegisterFlags(fs *flag.FlagSet) {
	fs.Func("max-streams-per-conn", "max concurrent streams per HTTP/2 connection", func(s string) error {
		v, err := strconv.ParseUint(s, 10, 32)
		o.MaxConcurrentStreamsPerConn = uint32(v)
		return err
	})
	fs.IntVar(&o.MaxInflightStreams, "max-inflight-streams", o.MaxInflightStreams, "global stream admission limit; 0 = unlimited")
	fs.IntVar(&o.MaxInflightUnary, "max-inflight-unary", o.MaxInflightUnary, "global unary admission limit; 0 = unlimited")
	fs.DurationVar(&o.MaxUnaryTimeout, "max-unary-timeout", o.MaxUnaryTimeout, "cap on unary deadlines; 0 = none")
	fs.DurationVar(&o.MaxConnectionAge, "max-connection-age", o.MaxConnectionAge, "GOAWAY after this age; 0 = infinity")
	fs.DurationVar(&o.MaxConnectionAgeGrace, "max-connection-age-grace", o.MaxConnectionAgeGrace, "close this long after the age GOAWAY; 0 = infinity")
}

// New builds the server. Interceptors run outermost first: metrics see every
// outcome, including rejections, recovered panics and drained streams.
func New(o Options, m *metrics.Server, d *Drainer) *grpc.Server {
	adm := newAdmission(o.MaxInflightUnary, o.MaxInflightStreams, m)
	opts := []grpc.ServerOption{
		grpc.StatsHandler(m.ConnStatsHandler()),
		grpc.ChainUnaryInterceptor(m.UnaryInterceptor, recoverUnary(m), adm.unary, capDeadline(o.MaxUnaryTimeout)),
		grpc.ChainStreamInterceptor(m.StreamInterceptor, recoverStream(m), adm.stream, d.StreamInterceptor),
		grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
			MinTime:             o.KeepaliveMinTime,
			PermitWithoutStream: o.KeepalivePermitWithoutStream,
		}),
		grpc.KeepaliveParams(keepalive.ServerParameters{
			MaxConnectionIdle:     o.MaxConnectionIdle,
			MaxConnectionAge:      o.MaxConnectionAge,
			MaxConnectionAgeGrace: o.MaxConnectionAgeGrace,
			Time:                  o.KeepaliveTime,
			Timeout:               o.KeepaliveTimeout,
		}),
	}
	if o.MaxConcurrentStreamsPerConn > 0 {
		opts = append(opts, grpc.MaxConcurrentStreams(o.MaxConcurrentStreamsPerConn))
	}
	if o.MaxRecvMsgSize > 0 {
		opts = append(opts, grpc.MaxRecvMsgSize(o.MaxRecvMsgSize))
	}
	if o.MaxSendMsgSize > 0 {
		opts = append(opts, grpc.MaxSendMsgSize(o.MaxSendMsgSize))
	}
	if o.MaxHeaderListSize > 0 {
		opts = append(opts, grpc.MaxHeaderListSize(o.MaxHeaderListSize))
	}
	if o.ConnectionTimeout > 0 {
		opts = append(opts, grpc.ConnectionTimeout(o.ConnectionTimeout))
	}
	return grpc.NewServer(opts...)
}
