package server

// Conformance tests: each one plays a toxic or unlucky client against a real
// server on loopback and asserts the protection holds. They use only the
// health service and raw HTTP/2, so they need nothing from this service's
// proto. Generated by vikrant; run in CI on every push.

import (
	"bytes"
	"context"
	"io"
	"net"
	"strings"
	"testing"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"golang.org/x/net/http2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/health"
	healthpb "google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"

	"github.com/smallStepGiantLeap/ledger/internal/platform/metrics"
)

func start(t *testing.T, o Options) string {
	t.Helper()
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	m := metrics.NewServer(prometheus.NewRegistry(), "test")
	srv := New(o, m, NewDrainer(0, nil))
	healthpb.RegisterHealthServer(srv, health.NewServer())
	go srv.Serve(lis)
	t.Cleanup(srv.Stop)
	return lis.Addr().String()
}

func dial(t *testing.T, addr string) *grpc.ClientConn {
	t.Helper()
	cc, err := grpc.NewClient(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { cc.Close() })
	return cc
}

// One connection cannot hold more than MaxConcurrentStreamsPerConn streams;
// the extra stream waits client-side instead of reaching the server.
func TestStreamsPerConnectionCapped(t *testing.T) {
	o := Defaults()
	o.MaxConcurrentStreamsPerConn = 2
	hc := healthpb.NewHealthClient(dial(t, start(t, o)))
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	for range 2 {
		w, err := hc.Watch(ctx, &healthpb.HealthCheckRequest{})
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Recv(); err != nil {
			t.Fatal(err)
		}
	}
	short, cancelShort := context.WithTimeout(ctx, 300*time.Millisecond)
	defer cancelShort()
	w, err := hc.Watch(short, &healthpb.HealthCheckRequest{})
	if err == nil {
		_, err = w.Recv()
	}
	if status.Code(err) != codes.DeadlineExceeded {
		t.Fatalf("third stream: got %v, want DeadlineExceeded (queued behind the cap)", err)
	}
}

// A message over MaxRecvMsgSize is rejected before any handler runs.
func TestOversizedMessageRejected(t *testing.T) {
	hc := healthpb.NewHealthClient(dial(t, start(t, Defaults())))
	_, err := hc.Check(context.Background(), &healthpb.HealthCheckRequest{Service: strings.Repeat("a", 5<<20)})
	if status.Code(err) != codes.ResourceExhausted {
		t.Fatalf("got %v, want ResourceExhausted", err)
	}
}

// Metadata over MaxHeaderListSize is refused.
func TestOversizedHeadersRejected(t *testing.T) {
	hc := healthpb.NewHealthClient(dial(t, start(t, Defaults())))
	if _, err := hc.Check(context.Background(), &healthpb.HealthCheckRequest{}); err != nil {
		t.Fatal(err) // the client learns the server's SETTINGS
	}
	ctx := metadata.AppendToOutgoingContext(context.Background(), "x-big", strings.Repeat("a", 32<<10))
	if _, err := hc.Check(ctx, &healthpb.HealthCheckRequest{}); err == nil {
		t.Fatal("32 KiB of metadata accepted; the limit is 16 KiB")
	}
}

// A client that connects and never speaks HTTP/2 is dropped after
// ConnectionTimeout instead of holding a socket for grpc-go's 120s.
func TestSilentConnectionClosed(t *testing.T) {
	o := Defaults()
	o.ConnectionTimeout = 300 * time.Millisecond
	conn, err := net.Dial("tcp", start(t, o))
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	start := time.Now()
	conn.SetReadDeadline(time.Now().Add(3 * time.Second))
	if _, err := io.Copy(io.Discard, conn); err != nil {
		t.Fatalf("connection not closed by the server: %v", err)
	}
	if el := time.Since(start); el > 1500*time.Millisecond {
		t.Fatalf("closed after %v, want about 300ms", el)
	}
}

// A client pinging faster than KeepaliveMinTime gets GOAWAY
// ENHANCE_YOUR_CALM "too_many_pings". Raw HTTP/2, because grpc-go's own
// client refuses to ping this often.
func TestPingFloodGetsGoAway(t *testing.T) {
	conn, err := net.Dial("tcp", start(t, Defaults()))
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	conn.SetDeadline(time.Now().Add(5 * time.Second))
	if _, err := conn.Write([]byte(http2.ClientPreface)); err != nil {
		t.Fatal(err)
	}
	fr := http2.NewFramer(conn, conn)
	if err := fr.WriteSettings(); err != nil {
		t.Fatal(err)
	}
	go func() {
		for i := range 20 {
			if fr.WritePing(false, [8]byte{byte(i)}) != nil {
				return
			}
		}
	}()
	for {
		f, err := fr.ReadFrame()
		if err != nil {
			t.Fatalf("no GOAWAY before %v", err)
		}
		if ga, ok := f.(*http2.GoAwayFrame); ok {
			if ga.ErrCode != http2.ErrCodeEnhanceYourCalm || !bytes.Contains(ga.DebugData(), []byte("too_many_pings")) {
				t.Fatalf("GOAWAY %v %q, want ENHANCE_YOUR_CALM too_many_pings", ga.ErrCode, ga.DebugData())
			}
			return
		}
	}
}

// --- Interceptor behaviour, tested directly -------------------------------

type fakeStream struct {
	grpc.ServerStream
	ctx context.Context
}

func (f *fakeStream) Context() context.Context { return f.ctx }

func testMetrics() *metrics.Server { return metrics.NewServer(prometheus.NewRegistry(), "test") }

func TestPanicBecomesInternal(t *testing.T) {
	_, err := recoverUnary(testMetrics())(context.Background(), nil, &grpc.UnaryServerInfo{FullMethod: "/t.S/M"},
		func(context.Context, any) (any, error) { panic("boom") })
	if status.Code(err) != codes.Internal {
		t.Fatalf("got %v, want Internal", err)
	}
}

func TestUnaryDeadlineCapped(t *testing.T) {
	start := time.Now()
	_, err := capDeadline(100*time.Millisecond)(context.Background(), nil, &grpc.UnaryServerInfo{FullMethod: "/t.S/M"},
		func(ctx context.Context, _ any) (any, error) {
			<-ctx.Done()
			return nil, status.FromContextError(ctx.Err()).Err()
		})
	if status.Code(err) != codes.DeadlineExceeded || time.Since(start) > time.Second {
		t.Fatalf("got %v after %v, want DeadlineExceeded after about 100ms", err, time.Since(start))
	}
}

func TestAdmissionShedsButHealthPasses(t *testing.T) {
	a := newAdmission(1, 1, testMetrics())
	release := make(chan struct{})
	busy := make(chan struct{})
	go a.unary(context.Background(), nil, &grpc.UnaryServerInfo{FullMethod: "/t.S/M"},
		func(context.Context, any) (any, error) { close(busy); <-release; return nil, nil })
	<-busy
	defer close(release)

	ok := func(context.Context, any) (any, error) { return nil, nil }
	if _, err := a.unary(context.Background(), nil, &grpc.UnaryServerInfo{FullMethod: "/t.S/M"}, ok); status.Code(err) != codes.ResourceExhausted {
		t.Fatalf("second call: got %v, want ResourceExhausted", err)
	}
	if _, err := a.unary(context.Background(), nil, &grpc.UnaryServerInfo{FullMethod: "/grpc.health.v1.Health/Check"}, ok); err != nil {
		t.Fatalf("health check shed under load: %v", err)
	}
}

// A handler that returns when its stream context is done drains without any
// code of its own, and the client is told UNAVAILABLE so it reconnects.
func TestDrainEndsStreamsWithUnavailable(t *testing.T) {
	d := NewDrainer(50*time.Millisecond, nil)
	errc := make(chan error, 1)
	go func() {
		errc <- d.StreamInterceptor(nil, &fakeStream{ctx: context.Background()}, &grpc.StreamServerInfo{FullMethod: "/t.S/Stream"},
			func(_ any, ss grpc.ServerStream) error {
				<-ss.Context().Done()
				return ss.Context().Err()
			})
	}()
	time.Sleep(20 * time.Millisecond)
	d.Drain()
	select {
	case err := <-errc:
		if status.Code(err) != codes.Unavailable {
			t.Fatalf("got %v, want Unavailable", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("stream not drained")
	}
}

// Health streams are exempt: the drain must not end the probes' view of the
// pod before the pod itself is gone.
func TestDrainSparesHealthStreams(t *testing.T) {
	d := NewDrainer(0, nil)
	d.Drain()
	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()
	err := d.StreamInterceptor(nil, &fakeStream{ctx: ctx}, &grpc.StreamServerInfo{FullMethod: "/grpc.health.v1.Health/Watch"},
		func(_ any, ss grpc.ServerStream) error {
			<-ss.Context().Done()
			return ss.Context().Err()
		})
	if status.Code(err) == codes.Unavailable {
		t.Fatal("health stream was drained")
	}
}
