#!/usr/bin/env bash
# Generated by vikrant v0.1.0 from service.yaml. Do not edit: platform-owned.
#
# Run ledger in a box and prove the platform's guarantees in a real mesh:
# a kind cluster with Istio (CNI, so no pod needs NET_ADMIN), Argo Rollouts,
# KEDA and Prometheus; this service and its dependencies deployed from their
# own generated manifests into PSS-restricted namespaces; callers simulated
# by identity. Every check below is derived from service.yaml and the proto.
#
#   e2e/run.sh          # up, deploy, test (idempotent; re-run freely)
#   e2e/run.sh down     # delete the cluster
#
# E2E_DEPS_DIR=<dir> uses <dir>/<name> for dependency repositories instead
# of cloning them from GitHub.
set -euo pipefail
cd "$(dirname "$0")/.."

NAME=ledger
ORG=smallStepGiantLeap
CLUSTER="${CLUSTER:-vikrant-e2e}"
CTX="kind-$CLUSTER"
ISTIO_VERSION=1.31.1
ARGO_ROLLOUTS_VERSION=v1.10.0
KEDA_VERSION=v2.21.0
WORK=e2e/.work
mkdir -p "$WORK" e2e/.bin e2e/.deps

k() { kubectl --context "$CTX" "$@"; }
log() { printf '%s  %s\n' "$(date +%H:%M:%S)" "$*" >&2; }

# --- the cluster and the platform ------------------------------------------

up() {
  if ! kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; then
    log "creating kind cluster $CLUSTER"
    kind create cluster --name "$CLUSTER" --config e2e/kind.yaml --wait 180s
  fi
  install_istio
  install_argo_rollouts
  install_keda
  log "installing prometheus"
  k apply -f e2e/platform/prometheus.yaml >/dev/null
  k -n monitoring rollout status deploy/prometheus --timeout=180s >/dev/null
}

install_istio() {
  if k -n istio-system get deploy istiod >/dev/null 2>&1; then return; fi
  local os arch
  case "$(uname -s)" in Darwin) os=osx ;; *) os=linux ;; esac
  case "$(uname -m)" in arm64 | aarch64) arch=arm64 ;; *) arch=amd64 ;; esac
  local asset="istioctl-$ISTIO_VERSION-$os-$arch.tar.gz"
  [[ "$os" == osx && "$arch" == amd64 ]] && asset="istioctl-$ISTIO_VERSION-osx.tar.gz"
  if [[ ! -x e2e/.bin/istioctl ]]; then
    log "downloading $asset"
    curl -sfL "https://github.com/istio/istio/releases/download/$ISTIO_VERSION/$asset" | tar -xz -C e2e/.bin
  fi
  log "installing istio $ISTIO_VERSION with the CNI plugin"
  # holdApplicationUntilProxyStarts: containers start only once the sidecar
  # is ready, so a probe's first call cannot race the proxy.
  local out
  if ! out="$(e2e/.bin/istioctl install -y --context "$CTX" \
    --set profile=minimal \
    --set components.cni.enabled=true \
    --set meshConfig.defaultConfig.holdApplicationUntilProxyStarts=true 2>&1)"; then
    echo "$out" >&2
    return 1
  fi
}

install_argo_rollouts() {
  if k -n argo-rollouts get deploy argo-rollouts >/dev/null 2>&1; then return; fi
  log "installing argo rollouts $ARGO_ROLLOUTS_VERSION"
  k create namespace argo-rollouts --dry-run=client -o yaml | k apply -f - >/dev/null
  # Server-side: the Rollout CRD is too large for client-side apply's
  # last-applied-configuration annotation (256 KiB limit).
  k apply --server-side --force-conflicts -n argo-rollouts \
    -f "https://github.com/argoproj/argo-rollouts/releases/download/$ARGO_ROLLOUTS_VERSION/install.yaml" >/dev/null
  k -n argo-rollouts wait --for=condition=Available deploy --all --timeout=180s >/dev/null
}

install_keda() {
  if k -n keda get deploy keda-operator >/dev/null 2>&1; then return; fi
  log "installing keda $KEDA_VERSION"
  k apply --server-side --force-conflicts -f "https://github.com/kedacore/keda/releases/download/$KEDA_VERSION/keda-${KEDA_VERSION#v}.yaml" >/dev/null
  # Every deployment, by condition: names change between KEDA releases.
  k -n keda wait --for=condition=Available deploy --all --timeout=180s >/dev/null
}

# --- services ---------------------------------------------------------------

image() { # dir name: build and load <name>:e2e
  log "building $2"
  docker build -q --provenance=false -t "$2:e2e" "$1" >/dev/null
  kind load docker-image --name "$CLUSTER" "$2:e2e" >/dev/null
}

deploy() { # dir name: apply the repo's own deploy/ with the e2e image
  # The base's images rule has already renamed the image to its registry
  # name, so the overlay matches that name.
  local overlay="$WORK/deploy-$2"
  mkdir -p "$overlay"
  # Two replicas instead of the default three: enough to show spread and
  # disruption rules, lighter on a laptop.
  cat >"$overlay/kustomization.yaml" <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [$(realpath --relative-to="$overlay" "$1/deploy" 2>/dev/null || python3 -c "import os,sys;print(os.path.relpath(sys.argv[1],sys.argv[2]))" "$1/deploy" "$overlay")]
images: [{name: ghcr.io/$(printf %s "$ORG" | tr '[:upper:]' '[:lower:]')/$2, newName: $2, newTag: e2e}]
patches:
  - target: {kind: Rollout, name: $2}
    patch: '[{"op":"replace","path":"/spec/replicas","value":2}]'
  - target: {kind: ScaledObject, name: $2}
    patch: '[{"op":"replace","path":"/spec/minReplicaCount","value":2}]'
EOF
  log "deploying $2"
  k apply -k "$overlay" >/dev/null
  wait_healthy "$2"
}

wait_healthy() { # name
  local deadline=$((SECONDS + 300)) phase=""
  while ((SECONDS < deadline)); do
    phase="$(k -n "$1" get rollout "$1" -o jsonpath='{.status.phase}' 2>/dev/null || true)"
    [[ "$phase" == Healthy ]] && return 0
    sleep 3
  done
  log "rollout $1 not healthy after 300s (phase: ${phase:-none})"
  k -n "$1" get pods -o wide >&2 || true
  k -n "$1" describe rollout "$1" | tail -20 >&2 || true
  return 1
}

dependency() { # name: a dependency repository, local or cloned
  local dir
  if [[ -n "${E2E_DEPS_DIR:-}" ]]; then
    dir="$E2E_DEPS_DIR/$1"
  else
    dir="e2e/.deps/$1"
    [[ -d "$dir/.git" ]] || git clone -q --depth 1 "https://github.com/$ORG/$1" "$dir"
    git -C "$dir" pull -q --ff-only || true
  fi
  image "$dir" "$1"
  deploy "$dir" "$1"
}

identity() { # namespace serviceaccount: a simulated caller, PSS-restricted and in the mesh
  k create namespace "$1" --dry-run=client -o yaml | k apply -f - >/dev/null
  k label --overwrite namespace "$1" istio-injection=enabled pod-security.kubernetes.io/enforce=restricted >/dev/null
  k -n "$1" create serviceaccount "$2" --dry-run=client -o yaml | k apply -f - >/dev/null
}

decoy() { # an undeclared service this one must not be able to reach
  k create namespace decoy --dry-run=client -o yaml | k apply -f - >/dev/null
  k -n decoy create deployment decoy --image="$NAME:e2e" --port=50051 --dry-run=client -o yaml | k apply -f - >/dev/null
  k -n decoy expose deployment decoy --port=50051 --dry-run=client -o yaml | k apply -f - >/dev/null
  k -n decoy rollout status deploy/decoy --timeout=120s >/dev/null
}

# --- probes -----------------------------------------------------------------

restricted='{"runAsNonRoot":true,"runAsUser":65532,"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"seccompProfile":{"type":"RuntimeDefault"}}'

probe_as() { # namespace serviceaccount app -- probe args: run as that identity
  local ns=$1 sa=$2 app=$3 pod="probe-$RANDOM$RANDOM"
  shift 4
  local args
  args="$(printf '"%s",' "$@")"
  k -n "$ns" run "$pod" --image=probe:e2e --image-pull-policy=IfNotPresent --restart=Never --labels="app=$app" \
    --overrides="{\"spec\":{\"serviceAccountName\":\"$sa\",\"securityContext\":{\"runAsNonRoot\":true,\"seccompProfile\":{\"type\":\"RuntimeDefault\"}},\"containers\":[{\"name\":\"$pod\",\"image\":\"probe:e2e\",\"args\":[${args%,}],\"securityContext\":$restricted}]}}" >/dev/null
  wait_terminated "$ns" "$pod" "{.status.containerStatuses[?(@.name==\"$pod\")].state.terminated.reason}"
  k -n "$ns" logs "$pod" -c "$pod" | tail -1
  k -n "$ns" delete pod "$pod" --wait=false >/dev/null
}

probe_inside() { # -- probe args: run inside this service's own pod
  shift
  local pod c="egress-$RANDOM$RANDOM"
  pod="$(k -n "$NAME" get pod -l app="$NAME" --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}')"
  # An ephemeral container shares the pod's network, sidecar, labels and
  # NetworkPolicy: exactly what the service itself would get.
  k -n "$NAME" debug "pod/$pod" --image=probe:e2e --image-pull-policy=IfNotPresent --profile=restricted \
    --container="$c" -- /probe "$@" >/dev/null 2>&1
  wait_terminated "$NAME" "$pod" "{.status.ephemeralContainerStatuses[?(@.name==\"$c\")].state.terminated.reason}"
  k -n "$NAME" logs "$pod" -c "$c" | tail -1
}

wait_terminated() { # namespace pod jsonpath
  local deadline=$((SECONDS + 60))
  while ((SECONDS < deadline)); do
    [[ -n "$(k -n "$1" get pod "$2" -o jsonpath="$3" 2>/dev/null)" ]] && return 0
    sleep 1
  done
}

# --- checks -----------------------------------------------------------------

passed=0
failed=0

matches() { # expectation output
  case "$1" in
  reach) [[ "$2" == CODE* && ! "$2" =~ (PermissionDenied|Unavailable|DeadlineExceeded) ]] ;;
  deny) [[ "$2" == "CODE PermissionDenied" ]] ;;
  blocked) [[ "$2" =~ ^CODE\ (PermissionDenied|Unavailable|DeadlineExceeded) ]] ;;
  dial-ok) [[ "$2" == "DIAL ok" ]] ;;
  dial-fail) [[ "$2" == DIAL\ failed* ]] ;;
  esac
}

check() { # expectation why -- command...: retried while the mesh converges
  local expect=$1 why=$2 out="" attempt
  shift 3
  for attempt in 1 2 3 4 5; do
    out="$("$@" 2>&1 || true)"
    matches "$expect" "$out" && break
    sleep 3
  done
  if matches "$expect" "$out"; then
    passed=$((passed + 1))
    printf 'PASS  %-9s %s\n      got: %s\n' "$expect" "$why" "$out"
  else
    failed=$((failed + 1))
    printf 'FAIL  %-9s %s\n      got: %s\n' "$expect" "$why" "$out"
  fi
}

skip() { # why: a check that cannot run yet, reported but not counted
  printf 'SKIP  %-9s %s\n' "" "$1"
}

assert() { # why -- command...: passes when the command succeeds
  local why=$1
  shift 2
  if "$@" >/dev/null 2>&1; then
    passed=$((passed + 1))
    printf 'PASS  %-9s %s\n' "" "$why"
  else
    failed=$((failed + 1))
    printf 'FAIL  %-9s %s\n' "" "$why"
  fi
}

if [[ "${1:-}" == down ]]; then
  kind delete cluster --name "$CLUSTER"
  exit 0
fi

up
image . "$NAME"
docker build -q --provenance=false -f e2e/Dockerfile.probe -t probe:e2e . >/dev/null
kind load docker-image --name "$CLUSTER" probe:e2e >/dev/null
deploy . "$NAME"
identity echo echo
identity intruder intruder
identity echo impostor
decoy

# --- assertions that are not single probes ----------------------------------

pss_pod() { # [capability...]: the rollout's pod template as a bare Pod, server-side dry run
  k -n "$NAME" get rollout "$NAME" -o json | python3 -c '
import json, sys
t = json.load(sys.stdin)["spec"]["template"]
c = t["spec"]["containers"][0]
c["image"] = sys.argv[1] + ":e2e"
if sys.argv[2:]:
    c["securityContext"]["capabilities"]["add"] = sys.argv[2:]
print(json.dumps({"apiVersion": "v1", "kind": "Pod", "metadata": {"generateName": "pss-", "namespace": sys.argv[1], "labels": t["metadata"].get("labels", {})}, "spec": t["spec"]}))
' "$NAME" "$@" | k create --dry-run=server -f -
}
refused() { ! "$@"; }
all_running_restricted() {
  [[ "$(k get ns "$NAME" -o jsonpath='{.metadata.labels.pod-security\.kubernetes\.io/enforce}')" == restricted ]] &&
    [[ -n "$(k -n "$NAME" get pod -l app="$NAME" -o name)" ]] &&
    [[ -z "$(k -n "$NAME" get pod -l app="$NAME" --field-selector=status.phase!=Running -o name)" ]]
}
eventually() { # seconds command...: retry until it succeeds
  local deadline=$((SECONDS + $1))
  shift
  until "$@"; do
    ((SECONDS < deadline)) || return 1
    sleep 2
  done
}
scaledobject_ready() {
  [[ "$(k -n "$NAME" get scaledobject "$NAME" -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')" == True ]]
}
canary_weight() { # weight
  [[ "$(k -n "$NAME" get virtualservice "$NAME" -o jsonpath='{.spec.http[0].route[1].weight}')" == "$1" ]]
}
promoted() { # old stable hash: the new revision is stable and healthy
  local stable current
  stable="$(k -n "$NAME" get rollout "$NAME" -o jsonpath='{.status.stableRS}')"
  current="$(k -n "$NAME" get rollout "$NAME" -o jsonpath='{.status.currentPodHash}')"
  [[ "$stable" != "$1" && "$stable" == "$current" ]] &&
    [[ "$(k -n "$NAME" get rollout "$NAME" -o jsonpath='{.status.phase}')" == Healthy ]]
}

echo
echo "== pod security"
assert "the rollout's pod template is admitted by PSS restricted" -- pss_pod
assert "the same pod with NET_ADMIN is refused (enforcement is live)" -- refused pss_pod NET_ADMIN
assert "every $NAME pod is running in the restricted namespace" -- all_running_restricted

echo
echo "== who may call $NAME (inbound)"
check reach "echo is granted ledger.v1.LedgerService/GetBalance" -- probe_as echo echo echo -- -target ledger.ledger.svc.cluster.local:50051 -method /ledger.v1.LedgerService/GetBalance
check deny "echo is not granted ledger.v1.LedgerService/Transfer: Istio denies it by identity" -- probe_as echo echo echo -- -target ledger.ledger.svc.cluster.local:50051 -method /ledger.v1.LedgerService/Transfer
check blocked "an undeclared namespace is stopped by NetworkPolicy before it reaches the mesh" -- probe_as intruder intruder intruder -- -target ledger.ledger.svc.cluster.local:50051 -method /ledger.v1.LedgerService/GetBalance
check deny "a pod in echo wearing app=echo but running as another service account passes NetworkPolicy; Istio denies it by identity" -- probe_as echo impostor echo -- -target ledger.ledger.svc.cluster.local:50051 -method /ledger.v1.LedgerService/GetBalance

echo
echo "== what $NAME may call (outbound, from inside its own pod)"
check blocked "decoy is not in outbound: the Sidecar and NetworkPolicy both refuse it" -- probe_inside -- -target decoy.decoy.svc.cluster.local:50051 -method /grpc.health.v1.Health/Check
check dial-fail "example.com is not in outbound" -- probe_inside -- -dial example.com:443

echo
echo "== autoscaling and rollout"
assert "KEDA scales the Rollout on in-flight RPCs (ScaledObject Ready)" -- eventually 120 scaledobject_ready
old="$(k -n "$NAME" get rollout "$NAME" -o jsonpath='{.status.stableRS}')"
k -n "$NAME" patch rollout "$NAME" --type merge -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"e2e/revision\":\"$RANDOM\"}}}}}" >/dev/null
assert "a new revision starts as a canary with 10% of traffic (Argo sets the VirtualService weight)" -- eventually 90 canary_weight 10
assert "the canary is promoted: analysis passes and the new revision is stable and Healthy" -- eventually 300 promoted "$old"
assert "after promotion the stable Service takes all traffic again" -- eventually 30 canary_weight 0

echo
echo "$passed passed, $failed failed (of $((6 + 7)) checks)"
[[ "$failed" -eq 0 ]]
