#!/usr/bin/env bash
# Generated by vikrant. Do not edit: platform-owned.
#
# Platform-owned files must match what vikrant rendered from service.yaml
# and the proto, as recorded in .platform/sha256sums. Two different states
# fail that comparison, and they are told apart instead of raced:
#
#   - service.yaml and the proto match the stamp, but a platform file does
#     not: it was edited by hand. That fails.
#   - service.yaml or the proto changed since the last render: the
#     platform's regeneration commit is on its way. In CI this waits for
#     the branch to move, then reports the commit as superseded (the newer
#     commit gets its own run); only if nothing arrives does it fail.
#
# Prints current=true|false for CI: a superseded commit skips e2e and
# publish, since its platform files are stale by definition.
set -euo pipefail
cd "$(dirname "$0")/.."
sums=.platform/sha256sums
out="${GITHUB_OUTPUT:-/dev/null}"

# Only --check and --quiet: GNU coreutils and macOS both have those.
grep -E '  (service\.yaml|proto/.+)$' "$sums" >"${TMPDIR:-/tmp}/vikrant-inputs.$$"
trap 'rm -f "${TMPDIR:-/tmp}/vikrant-inputs.$$"' EXIT
if sha256sum --check --quiet "${TMPDIR:-/tmp}/vikrant-inputs.$$" >/dev/null 2>&1; then
  if sha256sum --check --quiet "$sums"; then
    echo "current=true" >>"$out"
    exit 0
  fi
  echo "a platform-owned file was edited by hand: the platform restores it on the next push" >&2
  exit 1
fi

echo "service.yaml or the proto changed after the platform last rendered this branch: regeneration is pending"
branch="${BRANCH:-}"
this="${COMMIT:-}"
if [[ -z "$branch" || -z "$this" ]]; then
  echo "push it: the platform regenerates the derived files on the same branch" >&2
  exit 1
fi
for _ in $(seq $(( ${STAMP_WAIT:-180} / 5 ))); do
  head="$(git ls-remote origin "refs/heads/$branch" | cut -f1)"
  if [[ -n "$head" && "$head" != "$this" ]]; then
    echo "superseded by $head, which CI checks in its own run"
    echo "current=false" >>"$out"
    exit 0
  fi
  sleep 5
done
echo "the platform has not regenerated $branch in ${STAMP_WAIT:-180}s; its webhook may have failed: use Regenerate on the vikrant site to see why" >&2
exit 1
