// Command probe calls one gRPC method, or dials one TCP address, and prints
// the outcome. The e2e test runs it inside the mesh under different
// identities to check who may call what. Generated by vikrant; platform-owned.
//
// It needs no generated code: an empty request is a valid (all-default)
// message of any type, and unknown response fields are ignored, so any unary
// or streaming method can be called by its path alone.
//
//	probe -target echo.echo.svc.cluster.local:50051 -method /echo.v1.EchoService/Echo
//	probe -target ledger.ledger.svc.cluster.local:50051 -method /ledger.v1.LedgerService/Watch -stream
//	probe -dial api.stripe.com:443
//	probe -target echo.echo.svc.cluster.local:50051 -method /echo.v1.EchoService/Echo -loop 60s
//
// Output is one line: "CODE <grpc code>", "DIAL ok|failed <error>", or with
// -loop, "LOOP calls=<n> failed=<n> codes=<code>:<n>,...".
package main

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"net"
	"os"
	"slices"
	"strings"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
)

func main() {
	target := flag.String("target", "", "host:port of the gRPC server")
	method := flag.String("method", "", "full method path, /package.Service/Method")
	stream := flag.Bool("stream", false, "call as a streaming method")
	dial := flag.String("dial", "", "instead of calling, complete a TLS handshake with host:port")
	timeout := flag.Duration("timeout", 5*time.Second, "deadline, per call with -loop")
	loop := flag.Duration("loop", 0, "call repeatedly for this long, on one connection, and tally the codes")
	interval := flag.Duration("interval", 50*time.Millisecond, "pause between calls with -loop")
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	if *dial != "" {
		// A full TLS handshake, with SNI, against a verified certificate. A
		// sidecar accepts TCP locally even when it will not forward it, so
		// only a completed handshake proves the destination is reachable.
		host, _, err := net.SplitHostPort(*dial)
		if err == nil {
			d := tls.Dialer{Config: &tls.Config{ServerName: host, MinVersion: tls.VersionTLS12}}
			var c net.Conn
			if c, err = d.DialContext(ctx, "tcp", *dial); err == nil {
				c.Close()
			}
		}
		if err != nil {
			fmt.Println("DIAL failed", err)
			return
		}
		fmt.Println("DIAL ok")
		return
	}

	cc, err := grpc.NewClient(*target, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	defer cc.Close()
	if *loop > 0 {
		tally(cc, *method, *stream, *loop, *interval, *timeout)
		return
	}
	if *stream {
		err = callStream(ctx, cc, *method)
	} else {
		err = cc.Invoke(ctx, *method, &emptypb.Empty{}, &emptypb.Empty{}, grpc.WaitForReady(true))
	}
	fmt.Println("CODE", status.Code(err))
}

// failure is what a caller would see as the service being unavailable. Any
// other code, even Unimplemented, is an answer from the service itself.
var failure = []codes.Code{codes.Unavailable, codes.DeadlineExceeded, codes.Internal, codes.Unknown, codes.Canceled}

func tally(cc *grpc.ClientConn, method string, stream bool, d, interval, timeout time.Duration) {
	counts := map[codes.Code]int{}
	calls, failed := 0, 0
	var first, last time.Time
	var firstErr error
	for end := time.Now().Add(d); time.Now().Before(end); time.Sleep(interval) {
		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		var err error
		if stream {
			err = callStream(ctx, cc, method)
		} else {
			err = cc.Invoke(ctx, method, &emptypb.Empty{}, &emptypb.Empty{}, grpc.WaitForReady(true))
		}
		cancel()
		c := status.Code(err)
		counts[c]++
		calls++
		if slices.Contains(failure, c) {
			failed++
			if firstErr == nil {
				first, firstErr = time.Now(), err
			}
			last = time.Now()
		}
	}
	var parts []string
	for c, n := range counts {
		parts = append(parts, fmt.Sprintf("%s:%d", c, n))
	}
	slices.Sort(parts)
	out := fmt.Sprintf("LOOP calls=%d failed=%d codes=%s", calls, failed, strings.Join(parts, ","))
	if firstErr != nil {
		out += fmt.Sprintf(" failing=%s..%s first=%q", first.Format("15:04:05.000"), last.Format("15:04:05.000"), status.Convert(firstErr).Message())
	}
	fmt.Println(out)
}

func callStream(ctx context.Context, cc *grpc.ClientConn, method string) error {
	s, err := cc.NewStream(ctx, &grpc.StreamDesc{ServerStreams: true, ClientStreams: true}, method, grpc.WaitForReady(true))
	if err != nil {
		return err
	}
	if err := s.SendMsg(&emptypb.Empty{}); err != nil {
		return err
	}
	if err := s.CloseSend(); err != nil {
		return err
	}
	return s.RecvMsg(&emptypb.Empty{})
}
